### ISSUE TITLE
Polacode just doesn't work

### ISSUE THREAD

**Issue by cateyes99** [octref/polacode#157]
I'm using **VSCode 1.52.1** on **Windows 10 Enterprise** (_Version 1909_), & have installed **Polacode 0.3.4**. Once launching it by typing the command `Polacode` in the Command Palette, it isn't actually functioning at all.

**Comment by jorgealfonsogarcia** [comment]
Hello!

I have the same situation. I just installed `Polacode` on `VSCode` for `Windows 10 Enterprise`, and the extension doesn't work.

This is the "about" info from the `VSCode` that I'm using:

```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

![polacode](https://user-images.githubusercontent.com/3460617/105618576-f32a5180-5db6-11eb-870d-79bb2471f67d.gif)

**Comment by PoleG97** [comment]
Same issue. Exactly the same

**Comment by PoleG97** [comment]
It's very common that you have downloaded a wrong extension (there are a lot extensions very similar).
Uninstall it and try this:
https://marketplace.visualstudio.com/items?itemName=mrrefactoring.polacode-fixed-edition
This working for me

**Comment by MartinVandersteen** [comment]
Same for me using Ubuntu 20.04. Polacode appears in the right panel but nothing updates when I select code.
I tried both "Polacode" and "Polacode Fixed edition"

**Comment by pzelnip** [comment]
That one doesn't seem to work for me, I get to the save dialog & save the file, but no code appears in the generated image. :shrug:

**Comment by alias404** [comment]
I am having the same issue as @jorgealfonsogarcia described.

**Comment by bigbigbo** [comment]
```bash
ERR panel.postMessage is not a function: TypeError: panel.postMessage is not a function
    at c:\Users\Administrator\.vscode-insiders\extensions\pnp.polacode-0.3.4\src\extension.js:126:15
    at g.fire (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at D.$acceptEditorPropertiesChanged (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:46643)
    at o._doInvokeHandler (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
    at o._invokeHandler (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
    at o._receiveRequest (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)
    at o._receiveOneMessage (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)
    at d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
    at g.fire (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at _.fire (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15662)
    at d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29890
    at g.fire (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at _.fire (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15662)
    at t._receiveMessage (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20920)
    at d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17806
    at g.fire (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at l.acceptChunk (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13027)
    at d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12375
    at Socket.S (d:\vscode-insider\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13321)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by MohamedAliRashad** [comment]
I think this extension is officially broken
[Polacode-2020](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.polacode-2019)
