### ISSUE TITLE
.png file is not saved

### ISSUE THREAD

**Issue by alexandair** [octref/polacode#2]
I get a dialog window to pick the name and folder and save a shot as a shot.png, but when I click OK nothing happens. File is not saved. I'm running VSCode on Windows 10 with the latest patches.

**Comment by octref** [comment]
Thanks for letting me know!

Do you see any errors in Help -> Developer Tools?

**Comment by alexandair** [comment]
"Save as" causes 2 errors:

mainThreadExtensionService.ts:43 [pnp.polacode]ENOENT: no such file or directory, open 'C:\C:\Users\aleksandar\Desktop\shot.png'
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 Error: ENOENT: no such file or directory, open 'C:\C:\Users\aleksandar\Desktop\shot.png'
	at Object.fs.openSync (fs.js:584:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
	at Object.fs.writeFileSync (fs.js:1326:33)
	at writeSerializedBlobToFile (C:\Users\aleksandar\.vscode\extensions\pnp.polacode-0.1.0\out\src\extension.js:9:10)
	at vscode.window.showSaveDialog.then.uri (C:\Users\aleksandar\.vscode\extensions\pnp.polacode-0.1.0\out\src\extension.js:23:17)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
	at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:524:491)

**Comment by dfinke** [comment]
I get the same error

**Comment by octref** [comment]
Sorry for the problem . Published 0.1.1 which should fix the problem. Can you give it a try again?

**Comment by alexandair** [comment]
It works now. Thanks for the quick fix.
