### ISSUE TITLE
Does not seem to work on Mac OS

### ISSUE THREAD

**Issue by jdk339** [octref/polacode#60]
Installed the plugin just fine and can open the default screen where it shows the instructions, but it will not let me paste anything into the view to generate a new image. Tried clicking and pasting everywhere inside the "Polacode" tab.

**Comment by id0Sch** [comment]
Hi, I just did it and it worked just fine.

**Comment by jeffschwartz** [comment]
@id0Sch what version of Mac OS are you running it on?

**Comment by id0Sch** [comment]
10.13.3

**Comment by jeffschwartz** [comment]
@id0Sch that's interesting. I'm running VSC 1.21.1 and the Polacode plugin version is 0.22. What versions of these are you running?

**Comment by id0Sch** [comment]
I was using VSC 1.19.1 and updated to 1.21.1 right now and it's still working.
Polacode version is 0.2.2 as well. #

**Comment by HusseinMorsy** [comment]
same problem.
VSC 1.21.1
Polacode 0.2.2
MacOS 10.3.3

**Comment by jeffschwartz** [comment]
# I've determined the cause of failure for my VSCode setup.
* Polacode fails when the [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) plugin is enabled.

## To test, I:
* disabled VSCodeVim and restarted VSCode, 
* and I was able to paste code into Polacode and save the generated file.

**<span style="color: orange">Because of the nature of VSCode due to its dynamic environment depending upon the assortment of plugins we have installed the reason for your failure might differ, as it could be due to some other plugin conflicting with Polacode.</span>**

**Comment by jeffschwartz** [comment]
I have uninstalled Polacode. It is the only plugin that I have installed (I have many) that can't coexist with Vim. Hopefully Polacode will be able to in a future release.

**Comment by brunogenaro** [comment]
Did you guys tried CMD C and then CMD V on the Polacode window? It took a while to me figure that out, but it worked!

**Comment by HusseinMorsy** [comment]
@brunogenaro Unfortunately, it does not work

**Comment by allenfantasy** [comment]
Same problem with @jeffschwartz here: Polacode would conflict with VSCodeVim.

It's a sad news because I rely on vim mode so much that it's quite impossible for me to code without it.

**Comment by mctep** [comment]
I had the same issue but in my case I used [Paste And Indent Plugin](https://github.com/rubymaniac/vscode-paste-and-indent) with redefined some keybindings:

```json
{
    "key": "cmd+V",
    "command": "pasteAndIndent.action",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "cmd+V",
    "command": "editor.action.clipboardPasteAction",
    "when": "!editorTextFocus"
  },
  {
    "key": "cmd+shift+V",
    "command": "editor.action.clipboardPasteAction",
    "when": "editorTextFocus && !editorReadonly"
  },
```

So I have removed this plugin and keybindings and the issue has gone.

**Comment by ldexterldesign** [comment]
FYI Nothing to do with vim for me - never installed in

**Comment by Frankcarvajal** [comment]
On s Mac I'm able to paste, however, it clips outside of the designated box which is unusual, and I have to command - until it fits in order to save a decent download of the screenshot.

**Comment by dvakatsiienko** [comment]
I confirm that VSCodeVim conflicts with Polacode. After VSCodeVim uninstall Polacode works fine. But the problem is... that I nedd VSCodeVim.

**Comment by mhigley** [comment]
No Vim package installed and yet, same problem.
> VSC-Insider 1.25.0
> Polacode 0.2.2
> MacOS 10.3.4

Polacode installed fine. After launching package with `shift+cmd+p`, a new blank window appears and I get the following error in the debug console.

```
[Extension Host] rejected promise not handled within 1 second (at Timeout._onTimeout (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:793:924))

ERR Cannot set property telemetryService of #<t> which has only a getter: TypeError: Cannot set property telemetryService of #<t> which has only a getter
    at t [as constructor] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3381:972)
    at t.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:109:694)
    at e._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1324:875)
    at e.createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1324:129)
    at e.instantiate (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2337:882)
    at t.doInstantiateEditorControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3335:65)
    at t.doCreateEditorControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3334:766)
    at t.doShowEditorControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3334:426)
    at t.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3334:132)
    at t.doShowEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4671:650)
    at t.doOpenEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4671:465)
    at t.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4671:104)
    at t.doOpenEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4221:114)
    at t.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4220:893)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3388:219
    at e.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1323:808)
    at t._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2828:909)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2828:625
    at n.Class.define.cancel.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:157:119)
    at t.executeCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2828:599)
    at e.$executeCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2981:976)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3038:737)
    at e._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3038:455)
    at e._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3037:529)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3037:298)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3036:206
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3039:324
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:170:917)
    at Socket.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:301:1016)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by nightire** [comment]
For anyone been suffered of this issue, try not to use keyboard shortcut, select text then click __View__ -> __Copy__, and then __Paste__ in polacode tab will do the trick.

**Comment by shreeshakl** [comment]
Installed Paste And Indent Plugin, it worked for me.  im using command+c and command+v to copy paste.

**Comment by neildocherty** [comment]
I can't even open the Polacode tab.

**Comment by garbanv** [comment]
it wont open the new tab..not working

**Comment by AaronCuddeback** [comment]
Same problem wont open new tab...

**Comment by neildocherty** [comment]
I've checked again and it seems to work (well, it _does_ work) 🚀 

Polacode 0.3.1
VSCode 1.33.1
OSX 10.14.4
